! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : dynho_StoichiomSP.f90
! Time                 : Fri Feb 10 12:04:04 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/simple_dynH
! Equation file        : dynho.kpp
! Output root filename : dynho
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE dynho_StoichiomSP

  USE dynho_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(5) :: CROW_JVRP = (/ &
       1,  2,  4,  5,  7 /)

  INTEGER, PARAMETER, DIMENSION(6) :: ICOL_JVRP = (/ &
       3,  1,  3,  2,  1,  1 /)

  INTEGER, PARAMETER, DIMENSION(6) :: IROW_JVRP = (/ &
       1,  2,  2,  3,  4,  3 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(5) :: CCOL_STOICM = (/ &
       1,  3,  6,  8, 10 /)

  INTEGER, PARAMETER, DIMENSION(9) :: IROW_STOICM = (/ &
       1,  3,  1,  2,  3,  2,  3,  1,  2 /)

  INTEGER, PARAMETER, DIMENSION(9) :: ICOL_STOICM = (/ &
       1,  1,  2,  2,  2,  3,  3,  4,  4 /)

  REAL(kind=dp), PARAMETER, DIMENSION(9) :: STOICM = (/ &
       2.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       -2.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp /)


END MODULE dynho_StoichiomSP

